### ISSUE TITLE
这个问题很奇怪啊

### ISSUE THREAD

**Issue by maoxt** [bypass-GFW-SNI/proxy#1]
time="2019-01-19T15:51:57+08:00" level=info msg="www.right.com.cn is IP-blocked"
time="2019-01-19T15:52:00+08:00" level=info msg="www.right.com.cn is IP-blocked"
time="2019-01-19T15:52:03+08:00" level=info msg="www.right.com.cn is IP-blocked"
time="2019-01-19T15:52:07+08:00" level=info msg="www.right.com.cn is IP-blocked"

恩山不是被墙的网址啊   日志显示锁了

**Comment by bypass-GFW-SNI** [comment]
原因见 **[其中](https://github.com/bypass-GFW-SNI/proxy#%E5%85%B6%E4%B8%AD).3**。

因为代理版本不带黑名单，推荐与浏览器插件一起使用，比如 SwitchyOmega 等。
